version: '3'

services:

  restmain:
    container_name: restmain
    build:
      context: .
      dockerfile: Dockerfile_main
    ports:
      - "8180:8080"
    depends_on:
      - restconfig
    environment:
      - ORG_EXAMPLE_CONFIGCLIENT_MP_REST_URL=http://restconfig:8080

    entrypoint: entrypoint

  restconfig:
    container_name: restconfig
    build:
      context: .
      dockerfile: Dockerfile_config
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://hello:5432/config_db?current_schema=public
    links:
     - "database:hello"
    
  database:
    ports:
      - "5432"
    image: "postgres"
    container_name: postgresql
    restart: always
    environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=P@ssw0rd
     - POSTGRES_DB=config_db