#use image base regarding the version of JAVA used in pom.xml
FROM eclipse-temurin:11

#copy the jar file to this image
COPY rest_config-*.jar rest_config.jar

# execute .jar
CMD [ "java", "-jar", "rest_config.jar" ]