version: '3.9'

services:
  db:
    ports:
      - "5432:5432"
    image: postgres
    container_name: postgres_db
    networks:
      default:
        aliases: 
          - postgres
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_USER=admin
      - POSTGRES_DB=config_db
  config:
    build:
      context: .
      dockerfile: Dockerfile.config
    depends_on:
      - db
    restart: always
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/config_db?current_schema=public
      - ORG_EXAMPLE_CONFIGS_CREATION_ENABLED=false
    ports:
      - "8080:8080"
  main:
    build:
      context: .
      dockerfile: Dockerfile.main
    depends_on:
      - config
    restart: always
    environment:
      - ORG_EXAMPLE_CONFIGCLIENT_MP_REST_URL=http://config:8080/
    ports:
      - "8081:8080"